# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Say Hello from Fastlane"
  lane :hello_world do
    sh "echo 'Hello World from Fastlane for iOS!'"
  end
end

platform :android do
  desc "Say Hello from Fastlane"
  lane :hello_world do
    sh "echo 'Hello World from Fastlane for Android!'"
  end
end
