name: React Native CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: <Enter the pipeline >
    runs-on: macos-latest # Which os you should put here?

    steps:
      # 1. How the pipeline know how to run which code?
      - name: 'What you should do here?'
        uses: <something>

        # 2. What dependencies you should install for building apps?

        # 3. How you are going to build your app?

        # 4. How we use Fastlane to deploy our apps?
